#+title: July 24, 2025

* Metrics
** Sleep Quality: 7/10
- Time to bed: : 01:15
- Wake time: : 08:15
- Total hours: 7 hours
- Quality notes: Somewhat restless, caused by porn.
** Health Tracking
*** Water - 72/120oz
*** Nutrition
**** Meals:
  + [X] Breakfast: Bagel sandwich with 2 eggs, 2 slices of Canadian bacon, and a slice of sharp cheddar. 16oz milk,  8oz orange juice
  + [X] Lunch: 8 pieces of chicken, ranch, and a parfait with raspberries and strawberries
  + [X] Dinner: Chips and salsa, kettle chips
  + Snacks:
    + 9 Oreos (4 after lunch, 5 after getting home)

* Morning Foundation [7/9]
** [X] Wake up, drink water
** [X] Read Scripture
** [X] Read a book (1689 London Baptist Confession)
** [X] Wash face
** [X] Mesalomine, probiotic
** [X] Eat breakfast
** [X] Review day's battle plan

* Work
- Worked on trying to fix the styling for Belle's crafts, but there's a :bug: that is causing the styling to not work.
- Came up with the project for the hackathon: a 2D game in the ggez game framework for Rust.

** Key wins:
- I'm starting to better understand rust and get comfortable with it.

* Family Focus
** Quality Time Minutes: 15
** Meaningful Interactions: 3

* Faith
** [X] Prayer
** [X] Bible Reading (Acts 11)
** [X] Theological Reading (1689 Confession)

* Evening Review
** Victories
- What went exceptionally well: I got a good head start on learning the tools I'll use when I start the hackathon tomorrow.

** Growth Areas
- What could improve: My driving was terrible today, and I accidentally hit the Odyssey in our driveway. I was struggling with anxiety and self-doubt a lot today, which I think was caused by my increased porn troubles over the past few weeks.

** Gratitude
- Three things, ideas, people etc. I'm grateful for:
  1. Belle, for always keeping me grounded and sane.
  2. My family, for being gracious with me even when I act like a fool or a erk.
  3. Spencer, for always being willing to chat even if there's other, older friends around. 

** Evening Routine
*** Tomorrow's Preparation [/]
- [ ] Setup tomorrows journal file
- [ ] Post priorities from [[file:~/Notes/obsidian-vault/org/projects.org][projects.org]] file
- [ ] Set clothes out for morning

* Daily Reflection
** Focus Score [4-10]:
** Energy Level [5-10]:
** Most Impactful Moment: Hitting the van (pun intended)
** Key Lesson: Pray often, so that you can refocus your mind on God and not be distracted or overwhelmed by everything going on.

* Notes & Insights
